"""JMdict parts of speech: code -> description, and default short labels."""

POS_DESCRIPTIONS = {
    'adj-f': 'noun or verb acting prenominally',
    'adj-i': 'adjective (keiyoushi)',
    'adj-ix': 'adjective (keiyoushi) - yoi/ii class',
    'adj-kari': "'kari' adjective (archaic)",
    'adj-ku': "'ku' adjective (archaic)",
    'adj-na': 'adjectival nouns or quasi-adjectives (keiyodoshi)',
    'adj-nari': 'archaic/formal form of na-adjective',
    'adj-no': "nouns which may take the genitive case particle 'no'",
    'adj-pn': 'pre-noun adjectival (rentaishi)',
    'adj-shiku': "'shiku' adjective (archaic)",
    'adj-t': "'taru' adjective",
    'adv': 'adverb (fukushi)',
    'adv-to': "adverb taking the 'to' particle",
    'aux': 'auxiliary',
    'aux-adj': 'auxiliary adjective',
    'aux-v': 'auxiliary verb',
    'conj': 'conjunction',
    'cop': 'copula',
    'ctr': 'counter',
    'exp': 'expressions (phrases, clauses, etc.)',
    'int': 'interjection (kandoushi)',
    'n': 'noun (common) (futsuumeishi)',
    'n-adv': 'adverbial noun (fukushitekimeishi)',
    'n-pr': 'proper noun',
    'n-pref': 'noun, used as a prefix',
    'n-suf': 'noun, used as a suffix',
    'n-t': 'noun (temporal) (jisoumeishi)',
    'num': 'numeric',
    'pn': 'pronoun',
    'pref': 'prefix',
    'prt': 'particle',
    'suf': 'suffix',
    'unc': 'unclassified',
    'v-unspec': 'verb unspecified',
    'v1': 'Ichidan verb',
    'v1-s': 'Ichidan verb - kureru special class',
    'v2a-s': "Nidan verb with 'u' ending (archaic)",
    'v2b-k': "Nidan verb (upper class) with 'bu' ending (archaic)",
    'v2b-s': "Nidan verb (lower class) with 'bu' ending (archaic)",
    'v2d-k': "Nidan verb (upper class) with 'dzu' ending (archaic)",
    'v2d-s': "Nidan verb (lower class) with 'dzu' ending (archaic)",
    'v2g-k': "Nidan verb (upper class) with 'gu' ending (archaic)",
    'v2g-s': "Nidan verb (lower class) with 'gu' ending (archaic)",
    'v2h-k': "Nidan verb (upper class) with 'hu/fu' ending (archaic)",
    'v2h-s': "Nidan verb (lower class) with 'hu/fu' ending (archaic)",
    'v2k-k': "Nidan verb (upper class) with 'ku' ending (archaic)",
    'v2k-s': "Nidan verb (lower class) with 'ku' ending (archaic)",
    'v2m-k': "Nidan verb (upper class) with 'mu' ending (archaic)",
    'v2m-s': "Nidan verb (lower class) with 'mu' ending (archaic)",
    'v2n-s': "Nidan verb (lower class) with 'nu' ending (archaic)",
    'v2r-k': "Nidan verb (upper class) with 'ru' ending (archaic)",
    'v2r-s': "Nidan verb (lower class) with 'ru' ending (archaic)",
    'v2s-s': "Nidan verb (lower class) with 'su' ending (archaic)",
    'v2t-k': "Nidan verb (upper class) with 'tsu' ending (archaic)",
    'v2t-s': "Nidan verb (lower class) with 'tsu' ending (archaic)",
    'v2w-s': "Nidan verb (lower class) with 'u' ending and 'we' conjugation (archaic)",
    'v2y-k': "Nidan verb (upper class) with 'yu' ending (archaic)",
    'v2y-s': "Nidan verb (lower class) with 'yu' ending (archaic)",
    'v2z-s': "Nidan verb (lower class) with 'zu' ending (archaic)",
    'v4b': "Yodan verb with 'bu' ending (archaic)",
    'v4g': "Yodan verb with 'gu' ending (archaic)",
    'v4h': "Yodan verb with 'hu/fu' ending (archaic)",
    'v4k': "Yodan verb with 'ku' ending (archaic)",
    'v4m': "Yodan verb with 'mu' ending (archaic)",
    'v4n': "Yodan verb with 'nu' ending (archaic)",
    'v4r': "Yodan verb with 'ru' ending (archaic)",
    'v4s': "Yodan verb with 'su' ending (archaic)",
    'v4t': "Yodan verb with 'tsu' ending (archaic)",
    'v5aru': 'Godan verb - -aru special class',
    'v5b': "Godan verb with 'bu' ending",
    'v5g': "Godan verb with 'gu' ending",
    'v5k': "Godan verb with 'ku' ending",
    'v5k-s': 'Godan verb - Iku/Yuku special class',
    'v5m': "Godan verb with 'mu' ending",
    'v5n': "Godan verb with 'nu' ending",
    'v5r': "Godan verb with 'ru' ending",
    'v5r-i': "Godan verb with 'ru' ending (irregular verb)",
    'v5s': "Godan verb with 'su' ending",
    'v5t': "Godan verb with 'tsu' ending",
    'v5u': "Godan verb with 'u' ending",
    'v5u-s': "Godan verb with 'u' ending (special class)",
    'v5uru': 'Godan verb - Uru old class verb (old form of Eru)',
    'vi': 'intransitive verb',
    'vk': 'Kuru verb - special class',
    'vn': 'irregular nu verb',
    'vr': 'irregular ru verb, plain form ends with -ri',
    'vs': 'noun or participle which takes the aux. verb suru',
    'vs-c': 'su verb - precursor to the modern suru',
    'vs-i': 'suru verb - included',
    'vs-s': 'suru verb - special class',
    'vt': 'transitive verb',
    'vz': 'Ichidan verb - zuru verb (alternative form of -jiru verbs)',
}

DEFAULT_SHORT_LABELS = {
    'adj-f': 'prenominal',
    'adj-i': 'i-adjective',
    'adj-ix': 'i-adjective',
    'adj-kari': 'archaic adjective',
    'adj-ku': 'archaic adjective',
    'adj-na': 'na-adjective',
    'adj-nari': 'archaic na-adjective',
    'adj-no': 'no-adjective',
    'adj-pn': 'pre-noun adjectival',
    'adj-shiku': 'archaic adjective',
    'adj-t': 'taru-adjective',
    'adv': 'adverb',
    'adv-to': 'adverb (to)',
    'aux': 'auxiliary',
    'aux-adj': 'auxiliary adjective',
    'aux-v': 'auxiliary verb',
    'conj': 'conjunction',
    'cop': 'copula',
    'ctr': 'counter',
    'exp': 'expression',
    'int': 'interjection',
    'n': 'noun',
    'n-adv': 'adverbial noun',
    'n-pr': 'proper noun',
    'n-pref': 'noun (prefix)',
    'n-suf': 'noun (suffix)',
    'n-t': 'temporal noun',
    'num': 'numeric',
    'pn': 'pronoun',
    'pref': 'prefix',
    'prt': 'particle',
    'suf': 'suffix',
    'unc': 'unclassified',
    'v-unspec': 'verb',
    'v1': 'ichidan verb',
    'v1-s': 'ichidan verb',
    'v2a-s': 'archaic verb',
    'v2b-k': 'archaic verb',
    'v2b-s': 'archaic verb',
    'v2d-k': 'archaic verb',
    'v2d-s': 'archaic verb',
    'v2g-k': 'archaic verb',
    'v2g-s': 'archaic verb',
    'v2h-k': 'archaic verb',
    'v2h-s': 'archaic verb',
    'v2k-k': 'archaic verb',
    'v2k-s': 'archaic verb',
    'v2m-k': 'archaic verb',
    'v2m-s': 'archaic verb',
    'v2n-s': 'archaic verb',
    'v2r-k': 'archaic verb',
    'v2r-s': 'archaic verb',
    'v2s-s': 'archaic verb',
    'v2t-k': 'archaic verb',
    'v2t-s': 'archaic verb',
    'v2w-s': 'archaic verb',
    'v2y-k': 'archaic verb',
    'v2y-s': 'archaic verb',
    'v2z-s': 'archaic verb',
    'v4b': 'archaic verb',
    'v4g': 'archaic verb',
    'v4h': 'archaic verb',
    'v4k': 'archaic verb',
    'v4m': 'archaic verb',
    'v4n': 'archaic verb',
    'v4r': 'archaic verb',
    'v4s': 'archaic verb',
    'v4t': 'archaic verb',
    'v5aru': 'godan verb',
    'v5b': 'godan verb',
    'v5g': 'godan verb',
    'v5k': 'godan verb',
    'v5k-s': 'godan verb',
    'v5m': 'godan verb',
    'v5n': 'godan verb',
    'v5r': 'godan verb',
    'v5r-i': 'godan verb',
    'v5s': 'godan verb',
    'v5t': 'godan verb',
    'v5u': 'godan verb',
    'v5u-s': 'godan verb',
    'v5uru': 'godan verb',
    'vi': 'intransitive',
    'vk': 'kuru verb',
    'vn': 'irregular nu verb',
    'vr': 'irregular ru verb',
    'vs': 'suru verb',
    'vs-c': 'su verb',
    'vs-i': 'suru verb',
    'vs-s': 'suru verb',
    'vt': 'transitive',
    'vz': 'zuru verb',
}

DESCRIPTION_TO_CODE = {d: c for c, d in POS_DESCRIPTIONS.items()}
